<a href="https://colab.research.google.com/github/SatheeshkumarArigela/b-18-ws-3/blob/main/day2WK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
2+3

5

In [4]:
import pandas as pd
dataset=pd.read_csv('Data.csv')

In [5]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [7]:
dataset.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [8]:
dataset.tail()

Country   Age   Salary Purchased
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [33]:
import pandas as pd
dataset=pd.read_csv('Salary_Data_SLR.csv')
print(dataset)

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0


In [34]:
X=dataset.iloc[:,0].values
Y=dataset.iloc[:,-1].values

In [35]:

X

array([ 1.1,  1.3,  1.5,  2. ,  2.2,  2.9,  3. ,  3.2,  3.2,  3.7,  3.9,
        4. ,  4. ,  4.1,  4.5,  4.9,  5.1,  5.3,  5.9,  6. ,  6.8,  7.1,
        7.9,  8.2,  8.7,  9. ,  9.5,  9.6, 10.3, 10.5])

In [36]:
Y

array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
        54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
        61111.,  67938.,  66029.,  83088.,  81363.,  93940.,  91738.,
        98273., 101302., 113812., 109431., 105582., 116969., 112635.,
       122391., 121872.])

In [37]:
X=X.reshape(-1,1)
print(X)

[[ 1.1]
 [ 1.3]
 [ 1.5]
 [ 2. ]
 [ 2.2]
 [ 2.9]
 [ 3. ]
 [ 3.2]
 [ 3.2]
 [ 3.7]
 [ 3.9]
 [ 4. ]
 [ 4. ]
 [ 4.1]
 [ 4.5]
 [ 4.9]
 [ 5.1]
 [ 5.3]
 [ 5.9]
 [ 6. ]
 [ 6.8]
 [ 7.1]
 [ 7.9]
 [ 8.2]
 [ 8.7]
 [ 9. ]
 [ 9.5]
 [ 9.6]
 [10.3]
 [10.5]]


In [38]:
X

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [39]:
Y

array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
        54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
        61111.,  67938.,  66029.,  83088.,  81363.,  93940.,  91738.,
        98273., 101302., 113812., 109431., 105582., 116969., 112635.,
       122391., 121872.])

In [42]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y)
print(X_train.shape)
print(X_test.shape)

(22, 1)
(8, 1)


In [44]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit_(X_train,Y_train)

AttributeError: ignored

In [45]:
LinearRegression()

LinearRegression()

In [ ]:
Y_pred=regressor

In [ ]:
from sklearn.metrics import r2_score


In [9]:
dataset.head(1)

Country   Age   Salary Purchased
0  France  44.0  72000.0        No

In [10]:
dataset.tail(2)

Country   Age   Salary Purchased
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [12]:
X=dataset.iloc[:,0:-1].values

In [13]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [14]:
Y=dataset.iloc[:,-1].values

In [15]:
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [20]:
from sklearn.impute import SimpleImputer 
import numpy as np
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [22]:
from math import remainder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
X=ct.fit_transform(X)
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [24]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
Y=le.fit_transform(Y)
print(Y)


[0 1 0 0 1 1 0 1 0 1]


In [26]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X[:,[-2,-1]]=sc.fit_transform(X[:,[-2,-1]])
print(X)


[[1.0 0.0 0.0 0.7588743615900191 0.7494732544921673]
 [0.0 0.0 1.0 -1.7115038793306812 -1.4381784072687536]
 [0.0 1.0 0.0 -1.2755547779917342 -0.8912654918285233]
 [0.0 0.0 1.0 -0.1130238410878752 -0.25320042381492147]
 [0.0 1.0 0.0 0.17760889313808956 2.357833340847479e-16]
 [1.0 0.0 0.0 -0.5489729424268224 -0.5266568815350365]
 [0.0 0.0 1.0 1.1102230246251565e-16 -1.0735697969752667]
 [1.0 0.0 0.0 1.3401398300419487 1.3875383225057691]
 [0.0 1.0 0.0 1.6307725642679132 1.752146932799256]
 [1.0 0.0 0.0 -0.25834020820085757 0.2937124916253087]]


In [29]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)
X_train

array([[0.0, 1.0, 0.0, -1.2755547779917342, -0.8912654918285233],
       [0.0, 1.0, 0.0, 0.17760889313808956, 2.357833340847479e-16],
       [1.0, 0.0, 0.0, -0.25834020820085757, 0.2937124916253087],
       [1.0, 0.0, 0.0, 0.7588743615900191, 0.7494732544921673],
       [0.0, 1.0, 0.0, 1.6307725642679132, 1.752146932799256],
       [1.0, 0.0, 0.0, -0.5489729424268224, -0.5266568815350365],
       [1.0, 0.0, 0.0, 1.3401398300419487, 1.3875383225057691],
       [0.0, 0.0, 1.0, -1.7115038793306812, -1.4381784072687536]],
      dtype=object)

In [30]:
X_test

array([[0.0, 0.0, 1.0, -0.1130238410878752, -0.25320042381492147],
       [0.0, 0.0, 1.0, 1.1102230246251565e-16, -1.0735697969752667]],
      dtype=object)

In [31]:
Y_train

array([0, 1, 1, 0, 0, 1, 1, 1])

In [32]:
Y_test

array([0, 0])